port: ":8083"

db:
  #  without docker
  #  host: "localhost"
  #  port: "5434"

  host: "order_db"
  port: "5432"
  username: "postgres"
  password: "password"
  dbname: "postgres"
  sslmode: "disable"

signing_key: "jj@&48w3#ksSFpawd!W@SODFDKsskdajwdfgvc@%56ds"