version: '3.8'

services:
  order-svc:
    build: ./order-svc
    ports:
      - 8083:8083
    depends_on:
      order_db:
        condition: service_healthy
    environment:
      - DB_PASSWORD=password
  user-svc:
    build: ./user-svc
    ports:
      - 8082:8082
    depends_on:
      user_db:
        condition: service_healthy
    environment:
      - DB_PASSWORD=password
  api-gateway:
    build: ./api-gateway
    ports:
      - 8081:8081

  user_db:
    container_name: user_db
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
#    command: ["bash", "-c", "pg_isready -U postgres -d postgres && psql -U postgres -d postgres -f /user-svc/schema/000001_init.up.sql"]

  order_db:
    container_name: order_db
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5434:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
#    command: ["bash", "-c", "pg_isready -U postgres -d postgres && psql -U postgres -d postgres -f /order-svc/schema/000001_init.up.sql"]
